### ISSUE TITLE
Bug, improper converting 

### ISSUE THREAD

**Issue by slavkaz001** [Json2CSharp/Json2CSharp-Toolkit#4]
Issue: Missing "query" in the class definition.

Input:
{"_source":{"includes":["hubmsgid"]}},"size":10,"query":"test"}  

Output:
    public class Source    {
        public List<string> includes { get; set; } 

    }

    public class Root    {
        public Source _source { get; set; } 

    }

**Comment by Json2CSharp** [comment]
Wow how did i messed this scenario up, thanks @slavkaz001  for letting me know !! Will fix this issue in the next few weeks,

Thanks & Stay safe !

**Comment by Json2CSharp** [comment]
Just noticed that the supplied JSON format is invalid, closed the bracket before the size property
![image](https://user-images.githubusercontent.com/67238834/88851261-33888880-d1f5-11ea-9fe2-09dec3ff894c.png)
